"""empty message

Revision ID: 1e7ce1d4f690
Revises: 160ea4e7a379
Create Date: 2024-06-14 01:43:07.837992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e7ce1d4f690'
down_revision = '160ea4e7a379'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('duties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('locked', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('locked_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_event_locked_by_user'), 'user', ['locked_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('duties', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_event_locked_by_user'), type_='foreignkey')
        batch_op.drop_column('locked_by')
        batch_op.drop_column('locked')

    # ### end Alembic commands ###
