"""empty message

Revision ID: 24b6c8603e4b
Revises: f1315e650699
Create Date: 2024-06-27 11:12:59.706831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24b6c8603e4b'
down_revision = 'f1315e650699'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cadets', schema=None) as batch_op:
        batch_op.alter_column('sex',
               existing_type=sa.VARCHAR(length=1),
               nullable=False)

    '''with op.batch_alter_table('duties', schema=None) as batch_op:
        batch_op.alter_column('locked_by',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)

    with op.batch_alter_table('refresh_sessions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('refresh_token_jti',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)'''

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    '''with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('refresh_sessions', schema=None) as batch_op:
        batch_op.alter_column('refresh_token_jti',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('duties', schema=None) as batch_op:
        batch_op.alter_column('locked_by',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)'''

    with op.batch_alter_table('cadets', schema=None) as batch_op:
        batch_op.alter_column('sex',
               existing_type=sa.VARCHAR(length=1),
               nullable=True)

    # ### end Alembic commands ###
