"""group specializations added

Revision ID: 632c52eba3f0
Revises: 3da60f32e179
Create Date: 2024-06-30 23:13:42.417784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '632c52eba3f0'
down_revision = '3da60f32e179'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specializations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    '''with op.batch_alter_table('duties', schema=None) as batch_op:
        batch_op.alter_column('locked_by',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)'''

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialization_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_groups_specializations', 'specializations', ['specialization_id'], ['id'])

    '''with op.batch_alter_table('refresh_sessions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('refresh_token_jti',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)'''

    '''with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)'''

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    '''with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)'''

    '''with op.batch_alter_table('refresh_sessions', schema=None) as batch_op:
        batch_op.alter_column('refresh_token_jti',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)'''

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_constraint('fk_groups_specializations', type_='foreignkey')
        batch_op.drop_column('specialization_id')

    '''with op.batch_alter_table('duties', schema=None) as batch_op:
        batch_op.alter_column('locked_by',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)'''

    op.drop_table('specializations')
    # ### end Alembic commands ###
