"""number of cadets changed to dynamic prop

Revision ID: f1315e650699
Revises: abed2f7f0257
Create Date: 2024-06-26 20:06:02.198357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1315e650699'
down_revision = 'abed2f7f0257'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_duties')

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_column('number_of_cadets')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_of_cadets', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
