"""empty message

Revision ID: faa452a74c66
Revises: 24b6c8603e4b
Create Date: 2024-06-27 14:13:50.873770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faa452a74c66'
down_revision = '24b6c8603e4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('users', schema=None) as batch_op:
        '''batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.UUID(),
               existing_nullable=False)'''
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=False)


    # ### end Alembic commands ###
