"""empty message

Revision ID: 487555f94133
Revises: e4ace540250d
Create Date: 2024-06-06 19:56:51.298450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '487555f94133'
down_revision = 'e4ace540250d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    ...

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    ...
    # ### end Alembic commands ###
