"""female duties

Revision ID: e4ace540250d
Revises: ef006e413ddc
Create Date: 2024-06-03 23:01:03.005982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4ace540250d'
down_revision = 'ef006e413ddc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cadets', schema=None) as batch_op:
        batch_op.alter_column('sex',
               existing_type=sa.BOOLEAN(),
               type_=sa.Enum('M', 'F'),
               existing_nullable=True)

    with op.batch_alter_table('duties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('female_duty', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('duties', schema=None) as batch_op:
        batch_op.drop_column('female_duty')

    with op.batch_alter_table('cadets', schema=None) as batch_op:
        batch_op.alter_column('sex',
               existing_type=sa.Enum('M', 'F'),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    # ### end Alembic commands ###
