"""empty message

Revision ID: e76f5858048f
Revises: 
Create Date: 2024-06-06 20:01:36.060177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e76f5858048f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('replacement_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('duty_replaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('duty_id', sa.Integer(), nullable=False),
    sa.Column('replaced_id', sa.Integer(), nullable=False),
    sa.Column('replacing_id', sa.Integer(), nullable=False),
    sa.Column('duty_role_id', sa.Integer(), nullable=False),
    sa.Column('replacement_type_id', sa.Integer(), nullable=True),
    sa.Column('contents', sa.String(length=500), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['duty_id'], ['duties.id'], ),
    sa.ForeignKeyConstraint(['duty_role_id'], ['duty_roles.id'], ),
    sa.ForeignKeyConstraint(['replaced_id'], ['cadets.id'], ),
    sa.ForeignKeyConstraint(['replacement_type_id'], ['replacement_types.id'], ),
    sa.ForeignKeyConstraint(['replacing_id'], ['cadets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cadets', schema=None) as batch_op:
        batch_op.alter_column('sex',
               existing_type=sa.BOOLEAN(),
               type_=sa.Enum('M', 'F'),
               existing_nullable=True)

    with op.batch_alter_table('duties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('female_duty', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('duties', schema=None) as batch_op:
        batch_op.drop_column('female_duty')

    with op.batch_alter_table('cadets', schema=None) as batch_op:
        batch_op.alter_column('sex',
               existing_type=sa.Enum('M', 'F'),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    op.drop_table('duty_replaces')
    op.drop_table('replacement_types')
    # ### end Alembic commands ###
