"""small upd in Course

Revision ID: 6185c6d81040
Revises: f0e36b95e069
Create Date: 2024-05-24 19:46:10.624600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6185c6d81040'
down_revision = 'f0e36b95e069'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cadets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pm_cell_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ak_cell_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('main_location_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_cadet_locations', 'locations', ['main_location_id'], ['id'])
        batch_op.create_foreign_key('fk_cadet_pm_cell', 'pm_cells', ['pm_cell_id'], ['id'])
        batch_op.create_foreign_key('fk_cadet_ak_cell', 'ak_cells', ['ak_cell_id'], ['id'])

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=50), nullable=False))

    with op.batch_alter_table('cadets', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cadet_ak_cell', type_='foreignkey')
        batch_op.drop_constraint('fk_cadet_pm_cell', type_='foreignkey')
        batch_op.drop_constraint('fk_cadet_locations', type_='foreignkey')
        batch_op.drop_column('main_location_id')
        batch_op.drop_column('ak_cell_id')
        batch_op.drop_column('pm_cell_id')

    # ### end Alembic commands ###
