"""empty message

Revision ID: 354c07c70475
Revises: 33221d187fb8
Create Date: 2024-06-13 16:07:14.444245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '354c07c70475'
down_revision = '33221d187fb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cadet_id', sa.Integer(), nullable=True))
        batch_op.alter_column('last_seen',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('last_seen',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_column('cadet_id')

    # ### end Alembic commands ###
