"""empty message

Revision ID: 36b5accd6d32
Revises: 1e7ce1d4f690
Create Date: 2024-06-15 10:11:45.025053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36b5accd6d32'
down_revision = '1e7ce1d4f690'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('duties', schema=None) as batch_op:
        batch_op.alter_column('locked_by',
               existing_type=sa.TEXT(length=32),
               type_=sa.String(length=32),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar')

    with op.batch_alter_table('duties', schema=None) as batch_op:
        batch_op.alter_column('locked_by',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(length=32),
               existing_nullable=True)

    # ### end Alembic commands ###
