"""empty message

Revision ID: b75794b8f2af
Revises: 
Create Date: 2024-06-10 15:37:08.815276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b75794b8f2af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('replacement_docs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cadet_id', sa.Integer(), nullable=True),
    sa.Column('contents', sa.String(length=500), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['cadet_id'], ['cadets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('duty_replacements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('duty_id', sa.Integer(), nullable=False),
    sa.Column('replaced_id', sa.Integer(), nullable=False),
    sa.Column('replacing_id', sa.Integer(), nullable=False),
    sa.Column('duty_role_id', sa.Integer(), nullable=False),
    sa.Column('replacement_doc_id', sa.Integer(), nullable=True),
    sa.Column('commentary', sa.String(length=300), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['duty_id'], ['duties.id'], ),
    sa.ForeignKeyConstraint(['duty_role_id'], ['duty_roles.id'], ),
    sa.ForeignKeyConstraint(['replaced_id'], ['cadets.id'], ),
    sa.ForeignKeyConstraint(['replacement_doc_id'], ['replacement_docs.id'], ),
    sa.ForeignKeyConstraint(['replacing_id'], ['cadets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('duty_replacements')
    op.drop_table('replacement_docs')
    # ### end Alembic commands ###
